// Popular Canvas LMS schools for autocomplete
export interface School {
  name: string;
  url: string;
  state?: string;
}

export const CANVAS_SCHOOLS: School[] = [
  // Universities
  { name: 'Arizona State University', url: 'canvas.asu.edu', state: 'AZ' },
  { name: 'Auburn University', url: 'auburn.instructure.com', state: 'AL' },
  { name: 'Baylor University', url: 'baylor.instructure.com', state: 'TX' },
  { name: 'Brigham Young University', url: 'byu.instructure.com', state: 'UT' },
  { name: 'Brown University', url: 'canvas.brown.edu', state: 'RI' },
  { name: 'California State University', url: 'calstate.instructure.com', state: 'CA' },
  { name: 'Carnegie Mellon University', url: 'canvas.cmu.edu', state: 'PA' },
  { name: 'Clemson University', url: 'clemson.instructure.com', state: 'SC' },
  { name: 'Colorado State University', url: 'colostate.instructure.com', state: 'CO' },
  { name: 'Cornell University', url: 'canvas.cornell.edu', state: 'NY' },
  { name: 'Duke University', url: 'canvas.duke.edu', state: 'NC' },
  { name: 'Florida International University', url: 'fiu.instructure.com', state: 'FL' },
  { name: 'Florida State University', url: 'fsu.instructure.com', state: 'FL' },
  { name: 'George Mason University', url: 'gmu.instructure.com', state: 'VA' },
  { name: 'George Washington University', url: 'gwu.instructure.com', state: 'DC' },
  { name: 'Georgia Institute of Technology', url: 'gatech.instructure.com', state: 'GA' },
  { name: 'Harvard University', url: 'canvas.harvard.edu', state: 'MA' },
  { name: 'Indiana University', url: 'iu.instructure.com', state: 'IN' },
  { name: 'Iowa State University', url: 'canvas.iastate.edu', state: 'IA' },
  { name: 'Johns Hopkins University', url: 'jhu.instructure.com', state: 'MD' },
  { name: 'Kansas State University', url: 'ksu.instructure.com', state: 'KS' },
  { name: 'Louisiana State University', url: 'lsu.instructure.com', state: 'LA' },
  { name: 'Miami University', url: 'miamioh.instructure.com', state: 'OH' },
  { name: 'Michigan State University', url: 'msu.instructure.com', state: 'MI' },
  { name: 'Mississippi State University', url: 'msstate.instructure.com', state: 'MS' },
  { name: 'New York University', url: 'nyu.instructure.com', state: 'NY' },
  { name: 'North Carolina State University', url: 'ncsu.instructure.com', state: 'NC' },
  { name: 'Northeastern University', url: 'northeastern.instructure.com', state: 'MA' },
  { name: 'Northwestern University', url: 'canvas.northwestern.edu', state: 'IL' },
  { name: 'Ohio State University', url: 'osu.instructure.com', state: 'OH' },
  { name: 'Oklahoma State University', url: 'canvas.okstate.edu', state: 'OK' },
  { name: 'Oregon State University', url: 'oregonstate.instructure.com', state: 'OR' },
  { name: 'Penn State University', url: 'psu.instructure.com', state: 'PA' },
  { name: 'Purdue University', url: 'purdue.instructure.com', state: 'IN' },
  { name: 'Rice University', url: 'canvas.rice.edu', state: 'TX' },
  { name: 'Rutgers University', url: 'rutgers.instructure.com', state: 'NJ' },
  { name: 'San Diego State University', url: 'sdsu.instructure.com', state: 'CA' },
  { name: 'Stanford University', url: 'canvas.stanford.edu', state: 'CA' },
  { name: 'Stony Brook University', url: 'stonybrook.instructure.com', state: 'NY' },
  { name: 'Temple University', url: 'temple.instructure.com', state: 'PA' },
  { name: 'Texas A&M University', url: 'tamu.instructure.com', state: 'TX' },
  { name: 'Texas Tech University', url: 'ttu.instructure.com', state: 'TX' },
  { name: 'UC Berkeley', url: 'bcourses.berkeley.edu', state: 'CA' },
  { name: 'UC Davis', url: 'canvas.ucdavis.edu', state: 'CA' },
  { name: 'UC Irvine', url: 'canvas.eee.uci.edu', state: 'CA' },
  { name: 'UC Los Angeles (UCLA)', url: 'ccle.ucla.edu', state: 'CA' },
  { name: 'UC San Diego', url: 'canvas.ucsd.edu', state: 'CA' },
  { name: 'UC Santa Barbara', url: 'ucsb.instructure.com', state: 'CA' },
  { name: 'University of Alabama', url: 'uab.instructure.com', state: 'AL' },
  { name: 'University of Arizona', url: 'arizona.instructure.com', state: 'AZ' },
  { name: 'University of Arkansas', url: 'uark.instructure.com', state: 'AR' },
  { name: 'University of Central Florida', url: 'ucf.instructure.com', state: 'FL' },
  { name: 'University of Chicago', url: 'canvas.uchicago.edu', state: 'IL' },
  { name: 'University of Cincinnati', url: 'uc.instructure.com', state: 'OH' },
  { name: 'University of Colorado Boulder', url: 'colorado.instructure.com', state: 'CO' },
  { name: 'University of Connecticut', url: 'uconn.instructure.com', state: 'CT' },
  { name: 'University of Delaware', url: 'udel.instructure.com', state: 'DE' },
  { name: 'University of Florida', url: 'ufl.instructure.com', state: 'FL' },
  { name: 'University of Georgia', url: 'uga.instructure.com', state: 'GA' },
  { name: 'University of Houston', url: 'uh.instructure.com', state: 'TX' },
  { name: 'University of Illinois', url: 'canvas.illinois.edu', state: 'IL' },
  { name: 'University of Iowa', url: 'uiowa.instructure.com', state: 'IA' },
  { name: 'University of Kansas', url: 'ku.instructure.com', state: 'KS' },
  { name: 'University of Kentucky', url: 'uk.instructure.com', state: 'KY' },
  { name: 'University of Maryland', url: 'umd.instructure.com', state: 'MD' },
  { name: 'University of Massachusetts', url: 'umass.instructure.com', state: 'MA' },
  { name: 'University of Michigan', url: 'umich.instructure.com', state: 'MI' },
  { name: 'University of Minnesota', url: 'canvas.umn.edu', state: 'MN' },
  { name: 'University of Missouri', url: 'umsystem.instructure.com', state: 'MO' },
  { name: 'University of Nebraska', url: 'canvas.unl.edu', state: 'NE' },
  { name: 'University of Nevada Las Vegas', url: 'unlv.instructure.com', state: 'NV' },
  { name: 'University of New Mexico', url: 'unm.instructure.com', state: 'NM' },
  { name: 'University of North Carolina', url: 'unc.instructure.com', state: 'NC' },
  { name: 'University of Notre Dame', url: 'canvas.nd.edu', state: 'IN' },
  { name: 'University of Oklahoma', url: 'ou.instructure.com', state: 'OK' },
  { name: 'University of Oregon', url: 'canvas.uoregon.edu', state: 'OR' },
  { name: 'University of Pennsylvania', url: 'canvas.upenn.edu', state: 'PA' },
  { name: 'University of Pittsburgh', url: 'canvas.pitt.edu', state: 'PA' },
  { name: 'University of South Carolina', url: 'sc.instructure.com', state: 'SC' },
  { name: 'University of South Florida', url: 'usf.instructure.com', state: 'FL' },
  { name: 'University of Southern California', url: 'usc.instructure.com', state: 'CA' },
  { name: 'University of Tennessee', url: 'utk.instructure.com', state: 'TN' },
  { name: 'University of Texas at Austin', url: 'utexas.instructure.com', state: 'TX' },
  { name: 'University of Utah', url: 'utah.instructure.com', state: 'UT' },
  { name: 'University of Virginia', url: 'uva.instructure.com', state: 'VA' },
  { name: 'University of Washington', url: 'canvas.uw.edu', state: 'WA' },
  { name: 'University of Wisconsin', url: 'canvas.wisc.edu', state: 'WI' },
  { name: 'Utah State University', url: 'usu.instructure.com', state: 'UT' },
  { name: 'Vanderbilt University', url: 'vanderbilt.instructure.com', state: 'TN' },
  { name: 'Virginia Tech', url: 'vt.instructure.com', state: 'VA' },
  { name: 'Wake Forest University', url: 'wfu.instructure.com', state: 'NC' },
  { name: 'Washington State University', url: 'wsu.instructure.com', state: 'WA' },
  { name: 'West Virginia University', url: 'wvu.instructure.com', state: 'WV' },
  { name: 'Yale University', url: 'yale.instructure.com', state: 'CT' },
  // Community Colleges
  { name: 'Austin Community College', url: 'austincc.instructure.com', state: 'TX' },
  { name: 'Broward College', url: 'broward.instructure.com', state: 'FL' },
  { name: 'Community College of Denver', url: 'ccd.instructure.com', state: 'CO' },
  { name: 'Dallas College', url: 'dcccd.instructure.com', state: 'TX' },
  { name: 'De Anza College', url: 'deanza.instructure.com', state: 'CA' },
  { name: 'Foothill College', url: 'foothill.instructure.com', state: 'CA' },
  { name: 'Houston Community College', url: 'hccs.instructure.com', state: 'TX' },
  { name: 'Miami Dade College', url: 'mdc.instructure.com', state: 'FL' },
  { name: 'Northern Virginia Community College', url: 'nvcc.instructure.com', state: 'VA' },
  { name: 'Santa Monica College', url: 'smc.instructure.com', state: 'CA' },
  // K-12
  { name: 'Clark County School District', url: 'ccsd.instructure.com', state: 'NV' },
  { name: 'Gwinnett County Public Schools', url: 'gcps.instructure.com', state: 'GA' },
  { name: 'Houston ISD', url: 'houstonisd.instructure.com', state: 'TX' },
  { name: 'Los Angeles Unified', url: 'lausd.instructure.com', state: 'CA' },
  { name: 'New York City Schools', url: 'nycdoe.instructure.com', state: 'NY' },
];

export function searchSchools(query: string): School[] {
  if (!query || query.length < 2) return [];
  const q = query.toLowerCase();
  return CANVAS_SCHOOLS.filter(
    (s) =>
      s.name.toLowerCase().includes(q) ||
      s.url.toLowerCase().includes(q) ||
      (s.state && s.state.toLowerCase().includes(q))
  ).slice(0, 8);
}
